### ISSUE TITLE
S3 store failing when used with IAM

### ISSUE THREAD

**Issue by volkanunsal** [markevans/dragonfly-s3_data_store#12]
I have been trying to configure this gem with IAM profiles. As per instructions in the README, I have set up my `dragonfly.rb` like so:

```ruby
datastore :s3,
      use_iam_profile: true,
      bucket_name: ENV['S3_BUCKET']
```

(Removed the access key and the secret.)

But in the production, I get the following error:

```
[fog][WARNING] Unable to fetch credentials: Connection refused - connect(2) for 169.254.169.254:80 (Errno::ECONNREFUSED)
  ArgumentError (Missing required arguments: aws_access_key_id, aws_secret_access_key):
```

Am I doing this right?

**Comment by benpickles** [comment]
You would need to own the particular EC2 instance to use IAM in that way (automatic authorisation to other AWS services).

I am using IAM to restrict a Dragonfly-specific AWS user to a specific S3 bucket - `:access_key_id` and `:secret_access_key` are still required to authorise the user.

**Comment by HeathNaylor** [comment]
Then we need to update the README correct? It states this:

```
:use_iam_profile      # boolean - if true, no need for access_key_id or secret_access_key
```
