### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by robotvert** [markevans/dragonfly-s3_data_store#19]
Hi,

Maybe I'm missing something but according to the documentation the file path can be set like so:
```
Dragonfly.app.store(some_file, path: 'some/path.txt')
```
but here I would always get the autogenerated path unless I did
```
Dragonfly.app.store(some_file, {}, path: 'some/path.txt')
```

Looks like the [parent gem's store method](https://github.com/markevans/dragonfly/blob/master/lib/dragonfly/app.rb#L197-L199) has 2 distinct hashes, the latter one being passed down to here.
Am I understanding it all wrong or is the doc simply outdated?

**Comment by markevans** [comment]
no you're absolutely right - corrected now. Thanks!
