### ISSUE TITLE
Crash With Rails 5.2

### ISSUE THREAD

**Issue by rdetert** [markevans/dragonfly-s3_data_store#31]
Looks like the Bootsnap gem, which ships with Rails 5.2, is having trouble. Dragonfly with a file datastore starts up fine.

/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/compile_cache/iseq.rb:12: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Comment by hellvinz** [comment]
This has nothing to do with the gem, the issue has been reported on bootsnap https://github.com/Shopify/bootsnap/issues/132
