### ISSUE TITLE
Add option "ignore_destroy"

### ISSUE THREAD

**Issue by bobbus** [markevans/dragonfly-s3_data_store#7]
We have a `production` bucket and a `development` bucket.
We regularly use a script to copy all files from `production` into `development`.
As there is no bucket copy feature given by amazon, the copy process takes a lot of time especially if multiple files where deleted in `development` since the last synchronization.
Also, if one of the developper remove a file in his local environment, it will be removed from s3 and other developer would get a file missing error.

Having an option `ignore_destroy` would make the synchronization a lot faster as it will only need to import created file since the last synchronization, it will also prevent any file missing due to a local modification by one of the developer.

If you are interested to integrate this feature into this project, please let me know and I will try to implement it.

**Comment by markevans** [comment]
sorry I didn't comment earlier on this - I'd rather not integrate it as it's quite a specific problem which can still be worked around in other ways, catching errors etc.
thanks
